export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#242a36",
        "inverse-surface": "#dde2f3",
        background: "#0e131f",
        "surface-container-low": "#161c28",
        "surface-container": "#1a202c",
        "surface-dim": "#0e131f",
        "on-primary-container": "#613b00",
        "surface-bright": "#343946",
        "outline-variant": "#534434",
        tertiary: "#c7c8ff",
        "on-primary-fixed-variant": "#653e00",
        "surface-container-lowest": "#080e1a",
        "secondary-fixed-dim": "#4edea3",
        "on-surface": "#dde2f3",
        secondary: "#4edea3",
        "inverse-primary": "#855300",
        outline: "#a08e7a",
        "secondary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-secondary-container": "#00311f",
        "on-secondary-fixed-variant": "#005236",
        "on-tertiary-fixed": "#07006c",
        "on-surface-variant": "#d8c3ad",
        primary: "#ffc174",
        "on-tertiary": "#1000a9",
        "on-primary": "#472a00",
        "tertiary-container": "#a7a9ff",
        "primary-fixed-dim": "#ffb95f",
        "primary-container": "#f59e0b",
        "on-background": "#dde2f3",
        "surface-container-highest": "#2f3542",
        "surface-variant": "#2f3542",
        error: "#ffb4ab",
        "on-primary-fixed": "#2a1700",
        "secondary-container": "#00a572",
        "inverse-on-surface": "#2b303d",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-tint": "#ffb95f",
        "primary-fixed": "#ffddb8",
        "on-tertiary-container": "#2b29bb",
        surface: "#0e131f",
        "tertiary-fixed": "#e1e0ff",
        "on-error": "#690005",
        "on-secondary-fixed": "#002113",
        "on-error-container": "#ffdad6",
        "on-secondary": "#003824",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        base: "4px",
        gutter: "20px",
        "margin-mobile": "16px",
        xl: "40px",
        "margin-desktop": "48px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xs: "4px",
      },
      fontFamily: {
        "metric-xl": ["Sora"],
        "body-md": ["Sora"],
        "display-lg": ["Sora"],
        "headline-lg-mobile": ["Sora"],
        "headline-md": ["Sora"],
        "headline-lg": ["Sora"],
        "body-lg": ["Sora"],
        "label-caps": ["JetBrains Mono"],
      },
      fontSize: {
        "metric-xl": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [],
};
